---
title: "pythons_ss"
output: html_document
date: "2023-02-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(vkmCites)
library(tidyverse)
library(ggplot2)
head(vkmCites::Pythons)
names(vkmCites::Pythons)
unique(vkmCites::Pythons$Taxon)
unique(vkmCites::Pythons$Importer)
unique(vkmCites::Pythons$Exporter)
unique(vkmCites::Pythons$Origin)
min(vkmCites::Pythons$Year)
max(vkmCites::Pythons$Year)
```
##Total imports
```{r}
library(viridis)
library(viridisLite)
#Plot_imports(data=vkmCites::Pythons, Species="Python bivittatus", fullTerms = FALSE)

oo=Plot_imports_tc(data=vkmCites::Pythons, Species="Python bivittatus", fullTerms = FALSE, min_year = 1975)
pp=Plot_imports_tc(data=vkmCites::Pythons, Species="Python regius", fullTerms = FALSE, min_year = 1975)
qq=Plot_imports_tc(data=vkmCites::Pythons, Species="Python reticulatus", fullTerms = FALSE, min_year = 1975)
```
##import of live animals and live eggs
```{r}
library(viridis)
#Plot_live_imports(data = vkmCites::Pythons, Species = "Python bivittatus")

aa=Plot_live_imports_tc(data = vkmCites::Pythons, Species = "Python bivittatus", min_year = 1975)
bb=Plot_live_imports_tc(data = vkmCites::Pythons, Species = "Python regius", min_year = 1975)
cc=Plot_live_imports_tc(data = vkmCites::Pythons, Species = "Python reticulatus", min_year = 1975)
```
##import of parts and products
```{r}
dd=Plot_product_imports_tc(data = vkmCites::Pythons, Species = "Python bivittatus", min_year = 1975)
ee=Plot_product_imports_tc(data = vkmCites::Pythons, Species = "Python regius", min_year = 1975)
ff=Plot_product_imports_tc(data = vkmCites::Pythons, Species = "Python reticulatus", min_year = 1975)
```
##Distribution maps
```{r}
library(red)
library(rnaturalearth)
gg=map_GBIF_locs(Species = "Python bivittatus")
hh=map_GBIF_locs(Species = "Python regius")
ii=map_GBIF_locs(Species = "Python reticulatus")
```
##Trade networks
```{r}
library(visNetwork)
jj=plot_python_trade_network(Taxon = "Python bivittatus", importer = "NO", min_year = 2010)
kk=plot_python_trade_network(Taxon = "Python regius", importer = "NO", min_year = 2010)
ll=plot_python_trade_network(Taxon = "Python reticulatus", importer = "NO", min_year = 2010)
mm=plot_python_trade_network_allsp(importer = "NO", min_year = 2010)
nn=plot_python_trade_network_allsp(importer = "NO", min_year = 1975)
```

#Trying to control th ecolours
```{r}
Plot_live_imports_tc(data = vkmCites::Pythons, Species = "Python bivittatus", min_year = 1975) 
Plot_live_imports_tc(data = vkmCites::Pythons, Species = "Python regius", min_year = 1975)
Plot_live_imports_tc(data = vkmCites::Pythons, Species = "Python reticulatus", min_year = 1975)
```


#Trying to get the plots in species-wise panels
First figure: 3-panel histograms
```{r}
library(gridExtra)
pv_fig1a=grid.arrange(oo,aa,dd,ncol=3)
pv_fig1a

ggsave("P.bivittatus_fig.1.pdf", pv_fig1a, width = 30, height = 8, units="cm")

ggsave("P.bivittatus_fig.1.tiff", pv_fig1a, width = 30, height = 8, units="cm", dpi=500, compression="lzw")

pr_fig1a=grid.arrange(pp,bb,ee,ncol=3)
pr_fig1a

ggsave("P.regius_fig.1.pdf", pr_fig1a, width = 30, height = 8, units="cm")

ggsave("P.regius_fig.1.tiff", pr_fig1a, width = 30, height = 8, units="cm", dpi=500, compression="lzw")

pret_fig1a=grid.arrange(qq,cc,ff,ncol=3)
pret_fig1a

ggsave("P.reticulatus_fig.1.pdf", pret_fig1a, width = 30, height = 8, units="cm")

ggsave("P.reticulatus_fig.1.tiff", pret_fig1a, width = 30, height = 8, units="cm", dpi=500, compression="lzw")
```


Second figure: Map and network side by side
ggsave did not work for the network
```{r}
#pv_fig2a=grid.arrange(gg,jj,ncol=2)
#pv_fig2a
library(targets)
library(webshot)
widget <- tar_visnetwork()
visSave(widget, "graph.html")
webshot("graph.html", file = "graph.png")

```

